# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (At 01:30 on Thursday.)
  schedule: [{cron: "30 1 * * 4"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🦑 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: images/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: none
          output_condition: data-changed
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
          
      - name: Push to github
        run: |
          set +e
          git checkout metrics-renders
          git config user.name "Mandakara Sadewa"
          git config user.email "mdswa@zxce3.net"
          sudo mv -f /metrics_renders/images/* ./images
          git add --all
          git commit -sm "chore: push metrics"
          git push
          
